##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.11.0-B13] date: [Thu Dec 17 14:09:48 CST 2020]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = main


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
HARDWARE/MQTT/onenet_mqtt.c\
HARDWARE/led/led.c\
HARDWARE/TFT/tft_driver.c\
HARDWARE/TFT/tft.c\
SYSTEM/simulation_model/simulation_model.c\
HARDWARE/Relay/Relay.c\
USER/Frost_Detection/Frost_Detection.c\
HARDWARE/key/key.c\
HARDWARE/beep/beep.c\
HARDWARE/FAN/fan.c\
HARDWARE/DHT11/dht11.c\
HARDWARE/ds18b20/ds18b20.c\
HARDWARE/UART_DISPLAY/UART_DISPLAY.c\
HARDWARE/UART_SENSOR/UART_SENSOR.c\
SYSTEM/wwdg/wwdg.c\
SYSTEM/iwdg/iwdg.c\
SYSTEM/delay/delay.c \
SYSTEM/sys/sys.c \
SYSTEM/usart/usart.c \
SYSTEM/tim/tim.c \
USER/system_stm32f10x.c \
USER/main.c \
CORE/core_cm3.c \
STM32F10x_FWLib/src/misc.c          \
STM32F10x_FWLib/src/stm32f10x_gpio.c  \
STM32F10x_FWLib/src/stm32f10x_rtc.c \
STM32F10x_FWLib/src/stm32f10x_iwdg.c   \
STM32F10x_FWLib/src/stm32f10x_wwdg.c   \
STM32F10x_FWLib/src/stm32f10x_tim.c \
STM32F10x_FWLib/src/stm32f10x_exti.c   \
STM32F10x_FWLib/src/stm32f10x_usart.c \
STM32F10x_FWLib/src/stm32f10x_rcc.c   \
STM32F10x_FWLib/src/stm32f10x_bkp.c \
STM32F10x_FWLib/src/stm32f10x_pwr.c \

# ASM sources
ASM_SOURCES =  \
startup_stm32f103xe.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F10X_HD \
-DUSE_STDPERIPH_DRIVER


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IHARDWARE/MQTT\
-IHARDWARE/TFT\
-ISYSTEM/simulation_model\
-IHARDWARE/Relay\
-IHARDWARE/key\
-IHARDWARE/led\
-IHARDWARE/beep\
-IHARDWARE/FAN\
-IUSER/Frost_Detection\
-IHARDWARE/DHT11\
-IHARDWARE/ds18b20\
-IHARDWARE/UART_DISPLAY\
-IHARDWARE/UART_SENSOR\
-ISYSTEM/wwdg\
-ISYSTEM/iwdg\
-ICORE \
-ISTM32F10x_FWLib/inc \
-ISYSTEM/delay \
-ISYSTEM/sys \
-ISYSTEM/usart \
-ISYSTEM/tim \
-IUSER \
-IHARDWARE/at24c02 \

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections --exec-charset=GBK

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections --exec-charset=GBK

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
CFLAGS+=-std=c11
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F103ZETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys -u _printf_float -u _scanf_float
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	@echo build $@
	@$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@echo build $@
	@$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	@echo build $@
	@$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	@$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
clean:
	-rm -fR $(BUILD_DIR)
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
